---
title: "AI for Mathematics and Optimization"

# author:
#   - name: "Niao He"
#   - name: "Zebang Shen"

# affiliations:
#   - name: "YOUR INSTITUTE NAME HERE"


author:
  - name: Niao He
    affiliation: 
      - ETH Zurich
  - name: Zebang Shen
    affiliation: ETH Zurich
---


## AI as a tool
- AI accelerates scientific research.
  - Examples from the course in the past two years:
- How does AI help? 
  - Data analysis, simulation, routine automation, etc.

## AI as a collaborator
- Focus of this semester: AI accelerates mathematical research.
  - Core intellecture challenge
    - formulating hypothesis/definition
    - design algorithms
    - proving theorems
    - constructing counterexamples


## Example: First Proof
<!-- ```{=html} -->
<iframe
  src="https://1stproof.org/"
  style="width:100%; height:80vh; border:0;"
  title="Example website">
</iframe>

## Course organization
- _Passive_ in previous semester:
  - Students are assigned with published papers.
  - Present the existing results in the paper in the end of the semester
- _Active_ in this semester:
  - Students are assigned with **open problems** with the ambition to solve it!
  - If succeed, lead to technical report or even **publications**.
  - More to be covered later.

## Part of a social experiment
- How AI helps students to study new/abstract/challenging materials?
- How AI helps students to solve open problems?

## Why can we expect this is achievable?
- Emergence of LLM
- Many evidentce showing the potential of LLM in mathematical research.
- We will discuss:
  - Success stories
  - Inspiration/Prompting techniques from the success stories

## Success stories

